[pytest]
testpaths = tests
markers =
    slow: marks tests as slow (deselect with '-m "not slow"')
filterwarnings =
    ignore:Pydantic V1 style.*:pydantic.warnings.PydanticDeprecatedSince20:langchain_community.llms.azureml_endpoint
    ignore:The configuration option.*:pytest.PytestDeprecationWarning:pytest_asyncio.plugin
asyncio_default_fixture_loop_scope = function
