# Part of the totodev_pub library.
# Repository: https://github.com/ToTo-LLC/totodev-pub


# Generated by CodiumAI
from totodev_pub.minor.flexargs import FlexArgs

import pytest


class TestFlexArgs:

    # FlexArgs can be initialized with a dictionary of argument specifications and a program purpose string.
    def test_init_with_dict_arg_spec(self):
        arg_spec = {'arg1': 'Description of arg1', '--arg2': 'Description of --arg2'}
        prog_purpose = 'Program purpose'
        flex_args = FlexArgs(arg_spec, prog_purpose)
    
        #assert flex_args.arg_spec == { (f"[{key}]" if key.startswith('-') and not key.endswith('=') else key): value for key,value in arg_spec.items()}
        assert flex_args.prog_purpose == prog_purpose
        assert flex_args.extra_info is None

    # FlexArgs can be initialized with a string of argument specifications and a program purpose string.
    def test_init_with_str_arg_spec(self):
        arg_spec = 'arg1 --arg2'
        prog_purpose = 'Program purpose'
        flex_args = FlexArgs(arg_spec, prog_purpose)
    
        expected_arg_spec = {'arg1': 'Description of arg1', '[--arg2]': 'Description of --arg2'}
    
        #assert flex_args.arg_spec == expected_arg_spec
        assert flex_args.prog_purpose == prog_purpose
        assert flex_args.extra_info is None

    # FlexArgs can be initialized with a dictionary of argument specifications, a program purpose string, and an optional dictionary of extra information.
    def test_init_with_extra_info(self):
        arg_spec = {'--arg1': 'Description of --arg1', '--arg2': 'Description of --arg2'}
        prog_purpose = 'Program purpose'
        extra_info = {'Section 1': 'Extra information 1', 'Section 2': 'Extra information 2'}
        flex_args = FlexArgs(arg_spec, prog_purpose, extra_info)
    
        arg_spec = { (f"[{key}]" if key.startswith('-') and not key.endswith('=') else key): value for key,value in arg_spec.items()}
        #assert flex_args.arg_spec == arg_spec
        assert flex_args.prog_purpose == prog_purpose
        assert flex_args.extra_info == extra_info

    # FlexArgs can handle optional positional arguments.
    def test_optional_positional_args(self):
        arg_spec = {'arg1': 'Description of arg1', '[arg2]': 'Description of [arg2]'}
        prog_purpose = 'Program purpose'
        flex_args = FlexArgs(arg_spec, prog_purpose)
    
        expected_pos_argspec_names = ['arg1', 'arg2']  
        expected_required_pos_arg_count = 1
    
        set(flex_args.required_pos_arg_names+flex_args.optional_pos_arg_names) == set(expected_pos_argspec_names)
        assert len(flex_args.required_pos_arg_names) == expected_required_pos_arg_count

    # FlexArgs can handle ellipses positional arguments.
    def test_ellipses_positional_args(self):
        arg_spec = {'arg1': 'Description of arg1', '[...]': 'Description of ...'}
        prog_purpose = 'Program purpose'
        flex_args = FlexArgs(arg_spec, prog_purpose)
    
        expected_pos_argspec_names = ['arg1', '...']
        expected_required_pos_arg_count = 1
    
        assert set(flex_args.required_pos_arg_names+flex_args.optional_pos_arg_names) == set(expected_pos_argspec_names)
        assert len(flex_args.required_pos_arg_names) == expected_required_pos_arg_count

    # FlexArgs can handle single character switch arguments.
    def test_single_char_switch_args(self):
        arg_spec = {'-a': 'Description of -a', '-b': 'Description of -b'}
        prog_purpose = 'Program purpose'
        flex_args = FlexArgs(arg_spec, prog_purpose)
    
        expected_switch_argspec_names = ['-a', '-b']
    
        assert set(flex_args.required_switch_names + flex_args.optional_switch_names) == set(expected_switch_argspec_names)